### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by atelles** [christophsturm/filepeek#10]
JCenter will be shut down on May, see this article: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Copy of Strikt [238](https://github.com/robfletcher/strikt/issues/238)

I can't properly import Strikt as a dependency using only MavenCentral because filepeek is missing there

**Comment by StefMa** [comment]
Fixed in https://github.com/christophsturm/filepeek/pull/11

`0.1.3` is published to [MavenCentral](https://search.maven.org/artifact/com.christophsturm/filepeek).
